['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp7u01er2b/solution_0.py", line 75, in <module>\n    print(Solution().maxValue(nums = [31,31,31,31], k = 2))\nTypeError: maxValue() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp7u01er2b/solution_1.py", line 75, in <module>\n    print(Solution().maxValue(nums = [25,17,5,11,19,23,3,15,26,28], k = 4))\nTypeError: maxValue() got an unexpected keyword argument \'nums\'\n']