['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmphgfuefd9/solution_0.py", line 71, in <module>\n    print(Solution().numberOfPairs(points = [[1,1],[2,2],[3,3]]))\nTypeError: numberOfPairs() got an unexpected keyword argument \'points\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmphgfuefd9/solution_1.py", line 71, in <module>\n    print(Solution().numberOfPairs(points = [[6,2],[4,4],[2,6]]))\nTypeError: numberOfPairs() got an unexpected keyword argument \'points\'\n']