['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpq7gm8b26/solution_0.py", line 69, in <module>\n    print(Solution().earliestSecondToMarkIndices(nums = [5,5,5], changeIndices = [3,2,1,3,2,1,3,2,1]))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpq7gm8b26/solution_0.py", line 63, in earliestSecondToMarkIndices\n    if can_mark_by_second(psi_val):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpq7gm8b26/solution_0.py", line 32, in can_mark_by_second\n    theta[tau] = epsilon\nIndexError: list assignment index out of range\n', 'Outputs do not match']