['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp9nc6ouft/solution_0.py", line 78, in <module>\n    print(Solution().maxMoves(kx = 0, ky = 0, positions = [[49,49],[48,48],[47,47]]))\nTypeError: maxMoves() got an unexpected keyword argument \'kx\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp9nc6ouft/solution_1.py", line 78, in <module>\n    print(Solution().maxMoves(kx = 0, ky = 0, positions = [[1,0],[2,1],[3,2],[4,3]]))\nTypeError: maxMoves() got an unexpected keyword argument \'kx\'\n']