['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpcxyvwe5m/solution_0.py", line 115, in <module>\n    print(Solution().countGoodIntegers(n = 2, k = 3))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpcxyvwe5m/solution_0.py", line 103, in countGoodIntegers\n    calculationResult = factorials[n]\nIndexError: list index out of range\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpcxyvwe5m/solution_1.py", line 115, in <module>\n    print(Solution().countGoodIntegers(n = 4, k = 2))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpcxyvwe5m/solution_1.py", line 103, in countGoodIntegers\n    calculationResult = factorials[n]\nIndexError: list index out of range\n']