['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp1rxz2ico/solution_0.py", line 53, in <module>\n    print(Solution().distanceSum(m = 2, n = 2, k = 2))\nTypeError: distanceSum() got an unexpected keyword argument \'m\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp1rxz2ico/solution_1.py", line 53, in <module>\n    print(Solution().distanceSum(m = 3, n = 5, k = 4))\nTypeError: distanceSum() got an unexpected keyword argument \'m\'\n']