['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp822khx5s/solution_0.py", line 36, in <module>\n    print(Solution().maxNumber(n = 7))\nTypeError: maxNumber() got an unexpected keyword argument \'n\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp822khx5s/solution_1.py", line 36, in <module>\n    print(Solution().maxNumber(n = 17))\nTypeError: maxNumber() got an unexpected keyword argument \'n\'\n']