['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmps7vtdq_6/solution_0.py", line 57, in <module>\n    print(Solution().sumOfPower(nums = [1,1,1,1], k = 2))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmps7vtdq_6/solution_0.py", line 49, in sumOfPower\n    increment = pow(2, n - count, MOD)\nTypeError: pow expected 2 arguments, got 3\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmps7vtdq_6/solution_1.py", line 57, in <module>\n    print(Solution().sumOfPower(nums = [10,20,30,40,50], k = 90))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmps7vtdq_6/solution_1.py", line 49, in sumOfPower\n    increment = pow(2, n - count, MOD)\nTypeError: pow expected 2 arguments, got 3\n']