['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp_t2n0831/solution_0.py", line 20, in <module>\n    from itertools import pairwise\nImportError: cannot import name \'pairwise\' from \'itertools\' (unknown location)\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp_t2n0831/solution_1.py", line 20, in <module>\n    from itertools import pairwise\nImportError: cannot import name \'pairwise\' from \'itertools\' (unknown location)\n']